# Mandatory settings

blog_theme: dark # Or use dark
name: karimmuya
paginate: 25
url: https://karimmuya.github.io
baseurl: ""


# Optional settings

about_enabled: true 
local_fonts: false
rss_enabled: false 
scrollappear_enabled: true 
tag_nav_enabled: false 
theme_toggle: false
social:
  dribbble:
  facebook:
  flickr: 
  github: karimmuya 
  linkedin: 
  twitter: KarimMuya
  email: kerimmuya@gmail.com
  bitcoin: 
  ethereum:
  gitlab: 
  youtube: 
  twitch: 
  discord: 
  tumblr:
  bitbucket:
  docker:
  instagram:
  keybase:
  medium: 
  spotify: 
  stackoverflow:
  steam: 



assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/icons
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
collections:
  my_tags:
    output: true
    # permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - vendor/
  - yarn.lock
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: /posts/page/:num/
# permalink: posts/:slug
